### ISSUE TITLE
"Invalid YAML front matter from README.md" when YAML front matter is empty

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#36]
Doesn't seem to be assuming default values at the moment?

```yaml
files: []
window:
  - terminal
```
